media: images
content:
  - name: contacts
    label: Contacts
    type: file
    path: content/contacts.json
    fields:
      - { name: title, label: Title, type: string }
      - name: items
        label: Items
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string, required: true }
          - { name: link, label: Link, type: string, required: true }

  - name: works
    label: Works
    type: file
    path: content/works.json
    fields:
      - { name: title, label: Title, type: string }
      - name: entries
        label: Entries
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string, required: true }
          - { name: description, label: Description, type: string, required: true }
          - { name: image, label: Image, type: image }
          - { name: body, label: Body, type: rich-text, required: true }