media:
  - name: images
    label: Images
    input: images
    output: /images

  - name: vectors
    label: Vectors
    input: images/icons
    output: /images/icons
    extensions: [svg]
    categories: [image]
content:
  - name: contacts
    label: Contacts
    type: file
    path: content/contacts.json
    fields:
      - name: title
        label: Title
        type: object
        fields:
          - { name: en, label: English, type: string, required: true }
          - { name: ru, label: Russian, type: string, required: true }
      - name: items
        label: Items
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string, required: true }
          - { name: link, label: Link, type: string, required: true }
          - name: icon
            label: Icon
            type: image
            required: true
            options:
              media: images/vectors
              categories: [image]
              extensions: [svg]

  - name: projects
    label: Projects
    type: file
    path: content/projects.json
    fields:
      - name: title
        label: Title
        type: object
        fields:
          - { name: en, label: English, type: string, required: true }
          - { name: ru, label: Russian, type: string, required: true }
      - name: items
        label: Items
        type: object
        list: true
        fields:
          - { name: image, label: Image, type: image, required: true }
          - name: title
            label: Title
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: ru, label: Russian, type: string, required: true }
          - name: body
            label: Body
            type: object
            fields:
              - { name: en, label: English, type: rich-text, required: true }
              - { name: ru, label: Russian, type: rich-text, required: true }
          - { name: link, label: Link, type: string, required: true }
