media:
  - name: images
    label: Images
    input: images
    output: /images

  - name: vectors
    label: Vectors
    input: images/icons
    output: /images/icons
    extensions: [svg]
    categories: [image]
    
content:
  - name: general
    label: General
    type: file
    path: content/general.json
    fields:
      # About Section
      - name: about
        label: About
        type: object
        fields:
          - { name: photo, label: Photo, type: image, required: true }
          - name: body
            label: Body
            type: object
            fields:
              - { name: en, label: English, type: rich-text, required: true }
              - { name: ru, label: Russian, type: rich-text, required: true }
              
      # Achievements Section
      - name: achievements
        label: Achievements
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string }
          - { name: body, label: Body, type: rich-text }
          - { name: link-title, label: Link title, type: string }
          - { name: link, label: Link, type: string }

      # Contacts Section
      - name: contacts
        label: Contacts
        type: object
        fields:
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string, required: true }
              - { name: name, label: Name, type: string, required: true }
              - { name: link, label: Link, type: string, required: true }
              - name: icon
                label: Icon
                type: image
                required: true
                options:
                  media: vectors
                  categories: [image]
                  extensions: [svg]

      # Skills Section
      - name: skills
        label: Skills
        type: object
        fields:
          - name: development
            label: Development
            type: object
            fields:
              - name: items
                label: Items
                type: object
                list: true
                fields:
                  - { name: title, label: Title, type: string, required: true }
                  - { name: icon, label: Icon, type: image, required: true, options: { media: vectors, extensions: [svg] } }

          - name: design
            label: Design
            type: object
            fields:
              - name: items
                label: Items
                type: object
                list: true
                fields:
                  - { name: title, label: Title, type: string, required: true }
                  - { name: icon, label: Icon, type: image, required: true, options: { media: vectors, extensions: [svg] } }

  - name: projects
    label: Projects
    type: file
    path: content/projects.json
    fields:
      - name: items
        label: Items
        type: object
        list: true
        fields:
          - { name: image, label: Image, type: image, required: true }
          - name: title
            label: Title
            type: object
            fields:
              - { name: en, label: English, type: string, required: true }
              - { name: ru, label: Russian, type: string, required: true }
          - name: body
            label: Body
            type: object
            fields:
              - { name: en, label: English, type: rich-text, required: true }
              - { name: ru, label: Russian, type: rich-text, required: true }
          - { name: link, label: Link, type: string, required: true }
